package com.example.project_demo.vo.models

data class Covid19(
    val Confirmed: Int,
    val Deaths: Int,
    val DevBy: String,
    val Hospitalized: Int,
    val NewConfirmed: Int,
    val NewDeaths: Int,
    val NewHospitalized: Int,
    val NewRecovered: Int,
    val Recovered: Int,
    val UpdateDate: String,
    val active: Int,
    val activePerOneMillion: Double,
    val cases: Int,
    val casesPerOneMillion: Int,
    val continent: String,
    val country: String,
    val critical: Int,
    val criticalPerOneMillion: Double,
    val deaths1: Int,
    val deathsPerOneMillion: Int,
    val oneCasePerPeople: Int,
    val oneDeathPerPeople: Int,
    val oneTestPerPeople: Int,
    val population: Int,
    val recovered1: Int,
    val recoveredPerOneMillion: Double,
    val tests: Int,
    val testsPerOneMillion: Int,
    val todayCases: Int,
    val todayDeaths: Int,
    val todayRecovered: Int,
    val updated: Long
)